name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - uses: actions/checkout@v3
    
    - name: Install Autotools
    - run: sudo apt-get install autotools-dev
    - run: sudo apt-get install autoconf
    
    - name: Install CHECK
    - run: mkdir $HOME/check && cd $HOME/check
    - run: git clone https://github.com/libcheck/check.git
    - run: autoreconf --install
    - run: ./configure
    - run: make
    - run: make check
    - run: make install
    - run: cd ${{ github.workspace }}
      
    - name: configure
      run: ./configure
      
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: make check
         
    - name: Run distcheck
      run: make distcheck
         
    - run: echo "🍏 This job's status is ${{ job.status }}."
