name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Print informations
      run: |
        echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
        echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
        echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    
    - uses: actions/checkout@v3
    
    - name: Install Autotools
      run: |
        sudo apt-get install autotools-dev
        sudo apt-get install autoconf
    
    - name: Install CHECK
      run: |
        mkdir $HOME/check && cd $HOME/check
        git clone https://github.com/libcheck/check.git
        ls
        autoreconf --install
        ./configure
        make
        make check
        make install
        cd ${{ github.workspace }}
      
    - name: configure
      run: ./configure
      
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: make check
         
    - name: Run distcheck
      run: make distcheck
         
    - run: echo "🍏 This job's status is ${{ job.status }}."
