name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependencies:

    runs-on: ubuntu-latest

    steps:
    - name: Print informations
      run: |
        echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
        echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
        echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    
    - uses: actions/checkout@v3
    
    - name: Install Autotools
      run: |
        sudo apt-get install autotools-dev
        sudo apt-get install autoconf
    
    - name: Install CHECK
      run: |
        mkdir $HOME/check && cd $HOME/check
        git clone https://github.com/libcheck/check.git
        cd check
        autoreconf --install
        ./configure
        sudo make
        sudo make check
        sudo make install

  build:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
    - name: Configure
      run: ./configure
      
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: make check
         
    - name: Run distcheck
      run: make distcheck
         
    - run: echo "🍏 This job's status is ${{ job.status }}."
